export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const CREATE_TODO = 'CREATE_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';

export const GET_MEMES_SUCCESS = 'GET_MEMES_SUCCESS';
export const CREATE_MEME = 'CREATE_MEME';
export const REMOVE_MEME = 'REMOVE_MEME';

export const REDUCE_NPC_HEALTH = 'REDUCE_NPC_HEALTH';

export const SET_NPC_STATE = 'SET_NPC_STATE';


